FIELD_CONDITIONAL_COMPARER = "CONDITIONAL_COMPARER"
FIELD_FREE_COMPARER = "FREE_COMPARER"

RULES_DIR = "./rules"
ALERTS_DIR = "./alerts"

ALERTS_FILE_EXTENSION = ""
RULES_FILE_EXTENSION = ".rul"

ALERT_DESCRIPTION_FIELD = "DESC"
ALERT_TAGS_FIELD = "TAGS"
ALERT_NAME_FIELD = "NAME"
ALERT_TYPE_FIELD = "TYPE"

ALERT_YELLOW = "yellow"
ALERT_GREEN = "green"
ALERT_RED = "red"
