FIELD_CONDITIONAL_COMPARER = "CONDITIONAL_COMPARER"
FIELD_FREE_COMPARER = "FREE_COMPARER"
FIELD_DATE_COMPARER = "DATE_COMPARER"

RULES_DIR = "./rules"
ALERTS_DIR = "./alerts"

ALERTS_FILE_EXTENSION = ""
RULES_FILE_EXTENSION = ".rul"

ALERT_DESCRIPTION_FIELD = "DESC"
ALERT_TAGS_FIELD = "TAGS"
ALERT_NAME_FIELD = "NAME"
ALERT_TYPE_FIELD = "TYPE"

ALERT_YELLOW = "yellow"
ALERT_GREEN = "green"
ALERT_RED = "red"

ALERTS_PER_PAGE = 5
PINED_ALERTS_PER_PAGE = 18

ALL_ALERTS_FILE = "allAlerts.db"

ALERT_TYPE_INDEX = 0
ALERT_NAME_INDEX = 1
ALERT_DESCRIPTION_INDEX = 2
ALERT_TAGS_INDEX = 3
